### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Akari0001** [Henry-Hiles/QuadraticBot2.0#11] opened 2022-06-26 04:01 UTC
Add bonus role entry please 

Check out the giveaway bot https://dasu.gg

**Comment by Henry-Hiles** [comment] 2022-06-26 22:44
Will do, do you mean like an entry multiplier for a role?

**Comment by Henry-Hiles** [comment] 2022-06-27 17:27
Alr sounds good.

**Comment by Henry-Hiles** [comment] 2022-07-09 17:36
A bit busy right now, but i will add this as soon as i have time.

**Comment by Henry-Hiles** [comment] 2022-07-12 16:24
Really? What is it?

**Comment by Henry-Hiles** [comment] 2022-07-12 17:28
> If the winner dm is off the giveaway will not end
> 
> Console says `cannot dm user`

Hey, i cannot reproduce this,for me it ends fine just doesnt dm  the user, if this is a problem, please open a new issue and use the bug report template.

**Comment by Henry-Hiles** [comment] 2022-07-12 17:47
Should be fixed as of latest commit, thanks for letting me know. In the future for errors could you create a new issue with the bug report template?

**Comment by Henry-Hiles** [comment] 2022-07-12 18:09
> Yep + i have a way for u to add bonus entries

What do you mean? My plan was to just push more to the array, but that would be a little weird with a large multiplier.

**Comment by Henry-Hiles** [comment] 2022-07-20 12:48
It also makes it confusing on how to join the giveaway.

**Comment by Henry-Hiles** [comment] 2022-07-21 13:11
Oh, then what was the button for?

**Comment by Henry-Hiles** [comment] 2022-07-21 13:11
Oh the cinammon button. Hmm. What if i just add it in the embed?

**Comment by Henry-Hiles** [comment] 2022-08-16 12:36
Yeah sorry 😅

Will try to add this week

**Comment by Henry-Hiles** [comment] 2022-08-29 18:29
I have finished the migration to v14, and i implemented this feature. I will test and if all goes well will deploy on Tuesday night / Wednesday.

**Comment by Henry-Hiles** [comment] 2022-08-31 13:36
Just pushed, should now be working.

**Closed by Henry-Hiles** 2022-08-31 13:36 UTC
Labels: enhancement, good first issue
